package com.example.metadataui.customer.detail.application;
import com.example.metadataui.card.condition.*; import com.example.metadataui.card.model.*; import com.example.metadataui.card.validation.CardDefinitionValidator; import com.example.metadataui.customer.detail.spi.*; import org.slf4j.*; import org.springframework.aop.support.AopUtils; import org.springframework.core.annotation.AnnotationUtils; import org.springframework.stereotype.Service; import java.util.*; import java.util.stream.*;
@Service public class CustomerDetailCardService {
 private static final Logger log=LoggerFactory.getLogger(CustomerDetailCardService.class); private final List<CustomerDetailCardProvider> providers; private final List<CardConditionEvaluator> evaluators; private final CardDefinitionValidator validator;
 public CustomerDetailCardService(List<CustomerDetailCardProvider> p,List<CardConditionEvaluator> e,CardDefinitionValidator v){providers=p;evaluators=e;validator=v;Set<String> codes=new HashSet<>();p.forEach(x->{if(!codes.add(x.cardCode()))throw new IllegalStateException("duplicate card code: "+x.cardCode());});}
 public CardPageDefinition getCards(CustomerDetailContext c){List<CardDefinition> cards=providers.stream().filter(p->matches(p,c)).filter(p->p.supports(c)).map(p->p.definition(c)).peek(validator::validate).map(x->filterActions(x,c)).sorted(Comparator.comparingInt(CardDefinition::getOrder).thenComparing(CardDefinition::getCode)).collect(Collectors.toList());log.info("customer detail metadata: tenant={}, user={}, customer={}, cards={}",c.getTenantId(),c.getUserId(),c.getCustomerId(),cards.stream().map(CardDefinition::getCode).collect(Collectors.toList()));return new CardPageDefinition("customer_detail",cards);}
 private boolean matches(CustomerDetailCardProvider p,CustomerDetailContext c){CardConditional a=AnnotationUtils.findAnnotation(AopUtils.getTargetClass(p),CardConditional.class);return a==null||evaluators.stream().allMatch(e->e.matches(a,c));}
 private CardDefinition filterActions(CardDefinition x,CustomerDetailContext c){return new CardDefinition(x.getCode(),x.getTitle(),x.getComponent(),x.getOrder(),x.getSpan(),x.getDataApi(),x.getLoadStrategy(),x.getPermission(),x.getProps(),x.getActions().stream().filter(a->a.getPermission()==null||c.getPermissions().contains(a.getPermission())).collect(Collectors.toList()));}
}
